### ISSUE TITLE
Option to prefer default values when available and/or example values, before random values

### ISSUE THREAD

**Issue by aaronsteers** [ghandic/jsf#109]
I also would like to be able to apply defaults to the default generation. 

Example from JSON Schema Faker, show the inputs and outputs:

![image](https://github.com/ghandic/jsf/assets/18150651/8d7d49a1-6698-4fc0-9247-f8b876b11fee)

You can see in the above example, that the generated sample is easy to read and understand. Whereas a randomly generated set of inputs would lose much valuable context.

The use case is that we define inputs for our application as JSON schema specifications, and we ask users to provide their input matching that specification. It is much preferrable to have those generated values defaulting to the actual default values: (1) becase it is easier to understand from a user perspective if they see 'items per batch' defaulting to something like `1000` and not `1235134523451345`, and (2) because in those cases, deleting the defaults has the expected effect or basically not overriding them. 

Another case would be an example URL value or an example region name. Seeing the example or default value gives a much stronger hint of what kind of inputs are actually required. (If you see `us-east-1` as the default, you are going to feel comfortable providing `us-west-2`, and you probably won't mistakenly type `US West (Oregon)`.)

As (apparently?) implemented in [JSON Schema Faker](https://json-schema-faker.js.org/), I could imagine adding a `use_defaults` and `use_examples` into the `generate()` method. 

![image](https://github.com/ghandic/jsf/assets/18150651/e3adbd82-7e6c-4e5c-a6de-15517d560bef)

Happy to contribute if this is something I could help with.

**Comment by ghandic** [comment]
Happy to have those options, PR welcome

**Comment by simon-schoonjans** [comment]
I gave it a go: see PR #110

**Comment by aaronsteers** [comment]
@simon-schoonjans - That PR looks great! I'm excited to try it out!

Will close this as resolved, and will circle back if I run into any issues.

Thanks so much!
