### ISSUE TITLE
generate_and_validate method does not return any json object

### ISSUE THREAD

**Issue by ayushbindlish** [ghandic/jsf#19]
Hi @ghandic 

generate_and_validate() method does not return any json object. If that is how it is meant to be, maybe I can rename it to "validate()" and generate a pull request.

**Comment by ghandic** [comment]
Sure! Thanks for checking that, feel free to raise a PR and add some tests too, if you make one validate method that basically just proxies to the validate function and then also have validate as a boolean option on generate that could wool and iterate through the generated objects to validate them. Then generate_and_validate is no longer needed

**Comment by ayushbindlish** [comment]
Thanks for the update. I'll raise a pull request soon.
