### ISSUE TITLE
Enums always coerced to strings

### ISSUE THREAD

**Issue by leobaldock** [ghandic/jsf#25]
The current enum implementation results in generated `int` and `float` data being coerced to `str` due to how Pydantic handles `Union` (see these [docs](https://pydantic-docs.helpmanual.io/usage/types/#unions)). Pydantic will coerce the input to the first type it can match in the `Union`, which in the current implementation of `JSFEnum` is always a string for integers and floats.
```
class JSFEnum(BaseSchema):
    enum: Optional[List[Union[str, int, float, None]]] = []
```

Pydantic offers the following recommendation to solve this issue:
> As such, it is recommended that, when defining Union annotations, the most specific type is included first and followed by less specific types.

However, it also issues a warning concerning `Union`s inside of `List` or `Dict` types:

> `typing.Union` also ignores order when [defined](https://docs.python.org/3/library/typing.html#typing.Union), so `Union[int, float] == Union[float, int]` which can lead to unexpected behaviour when combined with matching based on the Union type order inside other type definitions, such as `List` and `Dict` types (because python treats these definitions as singletons). For example, `Dict[str, Union[int, float]] == Dict[str, Union[float, int]]` with the order based on the first time it was defined. Please note that this can also be [affected by third party libraries](https://github.com/samuelcolvin/pydantic/issues/2835) and their internal type definitions and the import orders.

Because of this I think the best solution is to use Pydantic's [Smart Union](https://pydantic-docs.helpmanual.io/usage/model_config/#smart-union) which will check the entire `Union` for the best type match before attempting to coerce.

**Comment by ghandic** [comment]
Sounds good, feel free to raise a PR 😃

**Comment by leobaldock** [comment]
Thanks for the swift reply!
