### ISSUE TITLE
Use random type when field is nullable

### ISSUE THREAD

**Issue by andrewshawcare** [ghandic/jsf#27]
In the following line:

https://github.com/ghandic/jsf/blob/3db751990962176f0659b713a1413cfba34c230a/src/jsf/parser.py#L78

A `TypeError` is raised when the item type represents more than one type (excluding `null`). I'm not sure why.

Can this method just return a random type from the list (including null)?

So:

```python
import random

...

def __is_field_nullable(self, schema: Dict[str, Any]) -> Tuple[str, bool]:
    item_type = schema.get("type")
    if isinstance(item_type, list):
        if "null" in item_type:
            return random.choice(item_type), True
    return item_type, False
```

**Comment by ghandic** [comment]
Absolutely! Looks like an artifact of building too specific to a spec I had. Please raise a PR

**Comment by andrewshawcare** [comment]
#28

**Comment by ghandic** [comment]
Could you run the test locally and get it passing? Looks like theres further changes required. I'll revert the merge until then

**Comment by andrewshawcare** [comment]
My apologies, the PR above passes tests locally (and in the pipeline).

**Comment by andrewshawcare** [comment]
Thanks for merging. When do you think you'll be making a new release? Thanks!
