### ISSUE TITLE
Pydantic 2.0 deprecations

### ISSUE THREAD

**Issue by abraha2d** [ghandic/jsf#73]
Pydantic 2 was released a few days ago... some of our tests are now failing with 
```
.env/lib/python3.11/site-packages/pydantic/_internal/_config.py:206: in prepare_config
    warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
E   pydantic.warnings.PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.0.1/migration/
        config     = <class 'jsf.schema_types.enum.JSFEnum.Config'>
```
(pytest is set up to treat warnings as errors)

Until deprecated usages are addressed, would it be possible to specify the requirement on `pydantic` as `>=1.10.4,<2` (instead of just `>=1.10.4`)?

**Comment by abraha2d** [comment]
As a side note, it looks like Pydantic has a tool that helps with migrating to Pydantic 2 (including addressing the warning that cause the above failure, see [here](https://github.com/pydantic/bump-pydantic#bp002-replace-config-class-by-model_config-attribute))

**Comment by ghandic** [comment]
Absolutely, feel free to submit a PR, we can support both versions of pydantic with v2 of jsf and v1 can limit the requirements to v1 pydantic
