### ISSUE TITLE
I have a simple json schema and I don't want to specify ContentEncoding for every field.

### ISSUE THREAD

**Issue by fxdgear** [ghandic/jsf#76]
```{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "accountUid": {
      "type": "string"
    }
  }
}
```

If I do the following: 

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from jsf import JSF

faker = JSF.from_json("simple.json")
fake_json = faker.generate()

print(fake_json)
```

I get the following error:

```
root@d42f6d379f02:/app# python basic.py 
/usr/local/lib/python3.10/site-packages/pydantic/_internal/_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'smart_union' has been removed
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/app/basic.py", line 6, in <module>
    faker = JSF.from_json("simple.json")
  File "/usr/local/lib/python3.10/site-packages/jsf/parser.py", line 208, in from_json
    return JSF(json.load(f))
  File "/usr/local/lib/python3.10/site-packages/jsf/parser.py", line 54, in __init__
    self._parse(schema)
  File "/usr/local/lib/python3.10/site-packages/jsf/parser.py", line 183, in _parse
    self.root = self.__parse_definition(name="root", path="#", schema=schema)
  File "/usr/local/lib/python3.10/site-packages/jsf/parser.py", line 141, in __parse_definition
    return self.__parse_object(name, path, schema)
  File "/usr/local/lib/python3.10/site-packages/jsf/parser.py", line 66, in __parse_object
    props.append(self.__parse_definition(_name, path=f"{path}/{_name}", schema=definition))
  File "/usr/local/lib/python3.10/site-packages/jsf/parser.py", line 156, in __parse_definition
    return self.__parse_primitive(name, path, schema)
  File "/usr/local/lib/python3.10/site-packages/jsf/parser.py", line 59, in __parse_primitive
    return cls.from_dict({"name": name, "path": path, "is_nullable": is_nullable, **schema})
  File "/usr/local/lib/python3.10/site-packages/jsf/schema_types/string.py", line 156, in from_dict
    return String(**d)
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for String
contentEncoding
  Field required [type=missing, input_value={'name': 'accountUid', 'p...False, 'type': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.3/v/missing
```

I can see here https://github.com/ghandic/jsf/pull/58 where you added support for ContentEncoding and in https://github.com/ghandic/jsf/issues/4 you even link to the spec of the json schema where it explains what the ContentEncodings are.

What I don't see is anyway for the default value to be used. IE I don't want to specify the ContentEncoding on each and every single field. As I'm going to have tens of schemas with hundreds of fields each that are not generated by me. Yet I need to figure out a way to generate and fake data for these schemas so we can automate some testing of ETL's. 

This being said I also noticed that when I put `"ContentEncoding": "8bit"` in my schema, it still failed. Apparently you're checking that the value is `8-bit`. Which according to the json schema docs is wrong. 

> The acceptable values are `7bit`, `8bit`, `binary`, `quoted-printable`, `base16`, `base32`, and `base64`. If not specified, the encoding is the same as the containing JSON document.

**Comment by ghandic** [comment]
You don't need to specify content encoding, the reason it's failing is it's using pydantic v2, we haven't done any testing on that yet.

**Comment by mtache** [comment]
Hi @ghandic,
Would it be acceptable to update this line: https://github.com/ghandic/jsf/blob/main/jsf/schema_types/string.py#L127 ?
From:
```
contentEncoding: Optional[content_encoding.ContentEncoding]
```
To:
```
contentEncoding: Optional[content_encoding.ContentEncoding] = None
```
Like the other fields ?
Indeed, how to define a field as optional as changed in pydantic v2 https://docs.pydantic.dev/2.1/migration/#required-optional-and-nullable-fields.

I've tested this and it worked fine.
